name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install libssl1.1 for mongodb-memory-server
        run: |
          wget http://snapshot.debian.org/archive/debian-security/20221201T000000Z/pool/updates/main/o/openssl1.1/libssl1.1_1.1.1n-0+deb11u4_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1n-0+deb11u4_amd64.deb

      - name: Install dependencies
        run: cd auth && npm install

      - name: Run tests
        run: cd auth && MONGOMS_VERSION=6.0.5 npm run test:ci
