name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: cd auth && npm install

      - name: Run tests
        run: cd auth && MONGOMS_VERSION=6.0.5 npm run test:ci
